# Generated by Django 3.2.3 on 2021-06-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floorsheet',
            fields=[
                ('contractId', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('stockSymbol', models.CharField(max_length=20)),
                ('buyerMemberId', models.PositiveIntegerField()),
                ('sellerMemberId', models.PositiveIntegerField()),
                ('contractQuantity', models.PositiveIntegerField()),
                ('contractRate', models.PositiveIntegerField()),
                ('contractAmount', models.PositiveBigIntegerField()),
                ('businessDate', models.DateField()),
                ('tradeBookId', models.PositiveIntegerField()),
                ('stockId', models.PositiveIntegerField()),
                ('buyerBrokerName', models.CharField(max_length=100)),
                ('sellerBrokerName', models.CharField(max_length=100)),
                ('tradeTime', models.DateTimeField()),
                ('securityName', models.CharField(max_length=100)),
            ],
        ),
    ]
