# Generated by Django 3.2.3 on 2021-06-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorsheet',
            name='buyerMemberId',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='floorsheet',
            name='sellerMemberId',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='floorsheet',
            name='stockId',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='floorsheet',
            name='tradeBookId',
            field=models.CharField(max_length=20),
        ),
    ]
